### ISSUE TITLE
graph --all option is unimplemented

### ISSUE THREAD

**Issue by rgobbel** [broadinstitute/wdltool#52]
The current version of wdltool doesn't appear to implement the --all option. This would be very useful. Any idea when it might be implemented? If it won't be any time soon, the documentation should reflect that.

**Comment by cjllanwarne** [comment]
This was actually removed because it created enormous and unreadable spaghetti in all but the simplest toy use cases. We should update the docs to remove mention of it.

If you really want to see the internal linkings of your workflow you could either
- Go back in time to before when it was removed (it looks like it was removed with [the addition of womgraph](https://github.com/broadinstitute/wdltool/pull/37))
- Check out the `wdltool womgraph` mode instead, which replaced it with a more rigorous (and perhaps even less readable) format

Either way, I'd warn you that it might sound more useful than it ended up being :)

**Comment by rgobbel** [comment]
Here's what happens when I try womgraph:

`[rgobbel@ussd-prd-rdln02]$ java -jar lib/wdltool-0.14.jar womgraph input_pipeline.wdl
Exception in thread "main" java.lang.Exception: Declaration not yet supported in WOM
        at wdl4s.wdl.WdlCall$.outputPortFromNode(WdlCall.scala:69)
        at wdl4s.wdl.WdlCall$.$anonfun$buildWomNodeAndInputs$5(WdlCall.scala:56)
        at scala.Option.map(Option.scala:146)
        at wdl4s.wdl.WdlCall$.$anonfun$buildWomNodeAndInputs$4(WdlCall.scala:55)
        at scala.Option.flatMap(Option.scala:171)
        at wdl4s.wdl.WdlCall$.$anonfun$buildWomNodeAndInputs$3(WdlCall.scala:54)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:378)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
        at scala.collection.immutable.List.flatMap(List.scala:341)
        at wdl4s.wdl.WdlCall$.$anonfun$buildWomNodeAndInputs$2(WdlCall.scala:53)
        at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:770)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:225)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:432)
        at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:769)
        at wdl4s.wdl.WdlCall$.wdl4s$wdl$WdlCall$$buildWomNodeAndInputs(WdlCall.scala:52)
        at wdl4s.wdl.WdlCall.x$4$lzycompute(WdlCall.scala:95)
        at wdl4s.wdl.WdlCall.x$4(WdlCall.scala:95)
        at wdl4s.wdl.WdlCall.womInputs$lzycompute(WdlCall.scala:95)
        at wdl4s.wdl.WdlCall.womInputs(WdlCall.scala:95)
        at wdl4s.wdl.WdlCall.womGraphInputNodes$lzycompute(WdlCall.scala:99)
        at wdl4s.wdl.WdlCall.womGraphInputNodes(WdlCall.scala:99)
        at wdl4s.wdl.WdlWorkflow$.$anonfun$buildWomGraph$1(WdlWorkflow.scala:54)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at wdl4s.wdl.WdlWorkflow$.buildWomGraph(WdlWorkflow.scala:53)
        at wdl4s.wdl.WdlWorkflow$.womWorkflowDefinition(WdlWorkflow.scala:69)
        at wdl4s.wdl.WdlWorkflow.womDefinition$lzycompute(WdlWorkflow.scala:86)
        at wdl4s.wdl.WdlWorkflow.womDefinition(WdlWorkflow.scala:86)
        at wdl4s.wdl.WdlNamespaceWithWorkflow.womExecutable$lzycompute(WdlNamespace.scala:76)
        at wdl4s.wdl.WdlNamespaceWithWorkflow.womExecutable(WdlNamespace.scala:76)
        at wdltool.graph.WomGraphPrint$.womExecutableFromWdl(WomGraphPrint.scala:27)
        at wdltool.graph.WomGraphPrint$.generateWorkflowDigraph(WomGraphPrint.scala:51)
        at wdltool.Main$.$anonfun$womGraph$2(Main.scala:100)
        at wdltool.Main$.continueIf(Main.scala:112)
        at wdltool.Main$.womGraph(Main.scala:96)
        at wdltool.Main$.dispatchCommand(Main.scala:38)
        at wdltool.Main$.delayedEndpoint$wdltool$Main$1(Main.scala:176)
        at wdltool.Main$delayedInit$body.apply(Main.scala:12)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:378)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at wdltool.Main$.main(Main.scala:12)
        at wdltool.Main.main(Main.scala)
`
